[package]
name = "tsunami"
version = "0.1.0"
edition = "2021"

[dependencies]
ssh2 = "0.9.4"
failure = "0.1.1"
tokio = { version = "1.21.2", features = ["full"] }
aws-config = "1.1.7"
aws-sdk-ec2 = "1.22.0"
